name: github-trending

on:
  schedule:
  - cron: "30 23 * * *"
  workflow_dispatch:

jobs:
  github-trending:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: npm install
        run: npm ci
        working-directory: .
      - name: fetch data
        run: node src/actions/github-trending.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
