name: ithome-daily

on:
  schedule:
  - cron: "30 15 * * *"
  workflow_dispatch:

jobs:
  ithome-daily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: npm install
        run: npm ci
        working-directory: .
      - name: fetch data
        run: node src/actions/ithome-daily.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
